name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o SDK .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore **/*.csproj

      - name: Compilar a aplicação
        run: dotnet build **/*.csproj --no-restore

      - name: Rodar testes (script personalizado)
        run: |
          echo "Iniciando testes..."
          dotnet test --no-build --verbosity normal